language: erlang
otp_release:
  - 19.0
  - 18.0
script:
  - $HOME/etcd/etcd &
  - $HOME/consul/consul agent -server -bootstrap-expect 1 -data-dir /tmp/consul &
  - "rm -rf .git && make tests"
addons:
cache:
  directories:
  - $HOME/etcd
  - $HOME/consul
before_install:
  - bash install-deps.sh